CC=gcc
CFLAGS=-Iinclude -c -Wall
LDFLAGS=

SRCDIR=src

SRC_COMMON=$(SRCDIR)/common/lh_common.c
OBJ_COMMON=$(SRC_COMMON:.c=.o)

SRC_NEEDLE=$(SRCDIR)/needle/needle.c
OBJ_NEEDLE=$(SRC_NEEDLE:.c=.o)

SRC_TESTAPP=$(SRCDIR)/testapp/testapp.c
OBJ_TESTAPP=$(SRC_TESTAPP:.c=.o)

all: needle testapp

needle: $(OBJ_COMMON) $(OBJ_NEEDLE)
	$(CC) $(LDFLAGS) $(OBJ_COMMON) $(OBJ_NEEDLE) -o bin/needle

#might be needed: -Wl,--export-dynamic
testapp: $(OBJ_COMMON) $(OBJ_TESTAPP)
	$(CC) $(LDFLAGS) $(OBJ_COMMON) $(OBJ_TESTAPP) -o bin/testapp

.o:
	@echo $< 
	$(CC) $(CFLAGS) $< -o $@

clean:
	-rm bin/* src/*/*.o
	exit 0
